repositorio/blog/apps/recetas/urls.py
from django.urls import include, path
from . import views  # Importamos las vistas de la aplicación

app_name='recetas'

urlpatterns = [
    # estructura de la ruta:
    # path('ruta', views.vista_a_ejecutar, name='nombre_ruta')
    # Ruta para la vista Home
    path('', views.ListarRecetas, name='listar'),
    path('detalle/<int:pk>', views.DetalleReceta, name = 'detalle'),
   
    
]

repositorio/blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views  # Importamos las vistas de la aplicación
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    
    # estructura de la ruta:
    # path('ruta', views.vista_a_ejecutar, name='nombre_ruta')
   
    #urls aplicaciones
    # path('noticias/', include('apps.noticias.urls')),
    path('', include('apps.paginas.urls')),  # Incluye las URLs de la app "paginas"
    path('', include('apps.articulos.urls')),  # Incluye las URLs de la app "articulos"
    path('', include('apps.usuarios.urls')),  # Incluye las URLs de la app "articulos"
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repositorio/blog/apps/recetas/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=30)
    
    def __str__(self) -> str:
        return self.nombre

class Recetas(models.Model):
    titulo = models.CharField(max_length=100)
    ingredientes = models.TextField()
    preparacion = models.TextField()
    nota = models.TextField()
    fecha_de_publicacion = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='recetas')
    categoria_receta = models.ForeignKey(Categoria, on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.titulo

repositorio/blog/apps/recetas/views.py
from django.shortcuts import render
from .models import Recetas, Categoria
from django.views.generic.list import ListView #para las vistas con class
# Create your views here.
def ListarRecetas(request):
    contexto = {}
    id_categoria = request.GET.get("id", None)
    if id_categoria:
        n = Recetas.objects.filter(categoria_receta = id_categoria)
    else:
        n = Recetas.objects.all() # es para que nos traiga todas las recetas que tengamos

    contexto['Recetas'] = n

    cat = Categoria.objects.all().order_by('nombre') #ordena la categoria por nombre
    contexto['categorias'] = cat

    return render(request, 'recetas/listar.html', contexto) 

def DetalleReceta(request, pk):
    contexto = {}

    n = Recetas.objects.get(pk = pk) # para que nos traiga solamente la receta que se elija

    contexto['Receta'] = n

    return render(request, 'recetas/detalle.html', contexto)

 

repositorio/blog/templates/recetas/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}RECETAS{% endblock titulo %}

{% block contenido %}
    <h1>AQUI ESTA UNA RECETA DETALLADA</h1>
    
    <img src="{{Receta.imagen.url}}" alt="" width="150px">
    <p>TITULO: {{Receta.titulo}} </p>
    <p>INGREDIENTES: {{Receta.ingredientes}} </p>
    <p>PREPARACION: {{Receta.preparacion}} </p>
    <p>NOTA: {{Receta.nota}} </p>
    <p>FECHA DE PUBLICACION: {{Receta.fecha_de_publicacion}} </p>
    <p>CATEGORIA: {{Receta.categoria_receta}} </p>
    
{% endblock contenido %}

repositorio/blog/templates/recetas/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}RECETAS{% endblock titulo %}

{% block contenido %}
    <h1>AQUI DEBERIAN LISTARSE LAS RECETAS</h1>

    <div class="submenu">
        <a href="{% url 'recetas:listar' %}"></a>
        {% for cat in categorias %}
            <a href="?id={{cat.pk}}"> {{cat.nombre}} </a>
        {% endfor %}
    </div>

    {% for r in Recetas %}
        <img src="{{r.imagen.url}}" alt="" width="150px">
        <p><a href="{% url 'recetas:detalle' r.pk %}">TITULO: {{r.titulo}}</a></p>
        <p>NOTA: {{r.nota}} </p>
        <p>FECHA DE PUBLICACION: {{r.fecha_de_publicacion}} </p>

    {% endfor %}

{% endblock contenido %}